/*
===============================================================================
Magnitude Analysis (Categorical Grouping & Comparisons)
===============================================================================
Script Purpose:
    - Compare core metrics (Revenue, Quantity, Customers, Products) across dimensions.
    - Analyze customer distribution by Country and Gender.
    - Evaluate product metrics (Count, Average Cost, Revenue) by Category.
    - Identify top revenue-generating customers and geographic sales volume.
===============================================================================
*/

-------------------------------------------------------------------------------
-- 1. Customer Demographics Magnitude
-------------------------------------------------------------------------------

-- Total Customers by Country
SELECT 
    country, 
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Total Customers by Gender
SELECT 
    gender, 
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender 
ORDER BY total_customers DESC;


-------------------------------------------------------------------------------
-- 2. Product Category Metrics
-------------------------------------------------------------------------------

-- Total Products by Category
SELECT 
    category, 
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category 
ORDER BY total_products DESC;

-- Average Product Cost by Category
SELECT 
    category, 
    AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;

-- Total Revenue Generated by Product Category
SELECT 
    p.category, 
    SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
    ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-------------------------------------------------------------------------------
-- 3. Customer & Geographical Performance
-------------------------------------------------------------------------------

-- Total Revenue Generated by Each Customer
SELECT 
    c.customer_key,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name, 
    SUM(s.sales_amount)                    AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
    ON s.customer_key = c.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- Distribution of Sold Items (Quantity) Across Countries
SELECT 
    c.country, 
    SUM(s.quantity) AS total_sold_quantity
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
    ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_quantity DESC;
